# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head1', models.CharField(max_length=120)),
                ('para1', models.TextField(blank=True)),
                ('para2', models.TextField(blank=True)),
                ('para3', models.TextField(blank=True)),
            ],
        ),
    ]
